### ISSUE TITLE
3D segmentation error

### ISSUE THREAD

**Issue by wuyanlin-wyl** [bowang-lab/MedSAMSlicer#2]
After selecting the Attach ROI, I encountered an error when clicking Segmentation. The following is the error message and screenshot of the interface
Traceback (most recent call last):
  File "D:/code/github/3D_Slicer_SAM/MedSAMSlicer/MedSAM/MedSAMLite/MedSAMLite.py", line 236, in <lambda>
    self.ui.pbSegment.connect('clicked(bool)', lambda: self.logic.applySegmentation())
  File "D:/code/github/3D_Slicer_SAM/MedSAMSlicer/MedSAM/MedSAMLite/MedSAMLite.py", line 606, in applySegmentation
    segmentation_mask = self.inferSegmentation(serverUrl)
  File "D:/code/github/3D_Slicer_SAM/MedSAMSlicer/MedSAM/MedSAMLite/MedSAMLite.py", line 579, in inferSegmentation
    response.raise_for_status()
  File "D:\software\3D_slicer\Slicer 5.7.0-2024-01-20\lib\Python\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:5555/infer
![4e5e2edeb520611bec6ac3bd0da47db](https://github.com/bowang-lab/MedSAMSlicer/assets/73480513/4b68b025-c442-4422-86ef-a1ac797aba75)
However, when choosing 2D Selection for segmentation, the segmentation was done correctly. Is there any solution? Thank you for your reply
![image](https://github.com/bowang-lab/MedSAMSlicer/assets/73480513/23951851-525b-4870-bb82-2f9243f22e26)

**Comment by naveen27b** [comment]
Hi, I am also facing the same issue. Were you able to resolve it? If yes, can you provide me the method. thanks a lot!!

**Comment by wuyanlin-wyl** [comment]
> Hi, I am also facing the same issue. Were you able to resolve it? If yes, can you provide me the method. thanks a lot!!

I haven't found a solution yet, so I can only achieve 3D effects through segmentation in the R and G dimensions

**Comment by rasakereh** [comment]
Thank you for sharing your experience. If there is no privacy concern, are you able to share the image file with me (reza.asakereh@uhn.ca) 
At the first image by @wuyanlin-wyl , I am also noticing a message in red before 'sending infer request...' Is it any different than the error message you mentioned here? 

For error reproducing purpose: do you use any preprocessing step? If not, would you try once with preprocessing?

Thanks

**Comment by matteo-bastico** [comment]
Hello, I have the same issue using the image FLARE22_Tr_0046_0000.nii.gz from [your Drive](https://drive.google.com/drive/folders/1ETWmi4AiniJeWOt6HAsYgTjYv_fkgzoN). I also use the CT pre-processing before sending the image.

![Screenshot from 2024-01-30 17-05-59](https://github.com/bowang-lab/MedSAMSlicer/assets/48530855/f1883bf3-bf57-497c-b76a-46929995a70f)

**Comment by rasakereh** [comment]
Thanks @matteo-bastico . Unfortunately I couldn't reproduce the error. Is it possible for you to provide more detail on reproducing it?
Btw we have a new [release](https://github.com/bowang-lab/MedSAMSlicer/releases/tag/v0.03) that might work fine for you. Also we implemented a better upgrade solution in the module so you dont have to do it manually each time after this version. Hope it fixes the bug.

**Comment by sarrabenyahia** [comment]
Hello, I am on the newest release and I have exactly the same problem. I unfortunately can't send the data but I can provide more info!

**Comment by JunMa11** [comment]
Hi @sarrabenyahia ,

Could you please record a video to reproduce this error?

**Comment by WanQian1997** [comment]
same problem with you,i cannoy solve it

**Comment by gaolidan** [comment]
![Q1_20240416140825](https://github.com/bowang-lab/MedSAMSlicer/assets/97864023/8ec29d61-1acf-49e6-a8b9-fb14341bd053)
Thank you so much for this nice extension, however, after selecting the Attach ROI, I encountered an error when clicking Segmentation.：
>>> 
Terminating possible server duplicates...
Running server...
[FD] D:\Slicer\MedSAMSlicer-master\server_essentials\tiny_vit_sam.py:662: UserWarning: Overwriting tiny_vit_5m_224 in registry with tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
[FD]   return register_model(fn_wrapper)
[FD] D:\Slicer\MedSAMSlicer-master\server_essentials\tiny_vit_sam.py:662: UserWarning: Overwriting tiny_vit_11m_224 in registry with tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
[FD]   return register_model(fn_wrapper)
[FD] D:\Slicer\MedSAMSlicer-master\server_essentials\tiny_vit_sam.py:662: UserWarning: Overwriting tiny_vit_21m_224 in registry with tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
[FD]   return register_model(fn_wrapper)
[FD] D:\Slicer\MedSAMSlicer-master\server_essentials\tiny_vit_sam.py:662: UserWarning: Overwriting tiny_vit_21m_384 in registry with tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
[FD]   return register_model(fn_wrapper)
[FD] D:\Slicer\MedSAMSlicer-master\server_essentials\tiny_vit_sam.py:662: UserWarning: Overwriting tiny_vit_21m_512 in registry with tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
[FD]   return register_model(fn_wrapper)
[FD] INFO:     Started server process [18712]
[FD] INFO:     Waiting for application startup.
[FD] INFO:     Application startup complete.
[FD] INFO:     Uvicorn running on http://0.0.0.0:5555 (Press CTRL+C to quit)
sending setImage request...
Response from setImage: null
sending numpy array:
sending infer request...
Traceback (most recent call last):
  File "D:/Slicer/MedSAMSlicer-master/MedSAM/MedSAMLite/MedSAMLite.py", line 284, in <lambda>
    self.ui.pbSegment.connect('clicked(bool)', lambda: self.logic.applySegmentation())
  File "D:/Slicer/MedSAMSlicer-master/MedSAM/MedSAMLite/MedSAMLite.py", line 834, in applySegmentation
    segmentation_mask = self.inferSegmentation(serverUrl)
  File "D:/Slicer/MedSAMSlicer-master/MedSAM/MedSAMLite/MedSAMLite.py", line 789, in inferSegmentation
    response.raise_for_status()
  File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:5555/infer
[FD] ERROR:    Exception in ASGI application
[FD] Traceback (most recent call last):
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
[FD]     result = await app(  # type: ignore[func-returns-value]
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
[FD]     return await self.app(scope, receive, send)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
[FD]     await super().__call__(scope, receive, send)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\applications.py", line 123, in __call__
[FD]     await self.middleware_stack(scope, receive, send)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
[FD]     raise exc
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
[FD]     await self.app(scope, receive, _send)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
[FD]     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
[FD]     raise exc
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
[FD]     await app(scope, receive, sender)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\routing.py", line 756, in __call__
[FD]     await self.middleware_stack(scope, receive, send)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\routing.py", line 776, in app
[FD]     await route.handle(scope, receive, send)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\routing.py", line 297, in handle
[FD]     await self.app(scope, receive, send)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\routing.py", line 77, in app
[FD]     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
[FD]     raise exc
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
[FD]     await app(scope, receive, sender)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\routing.py", line 72, in app
[FD]     response = await func(request)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\fastapi\routing.py", line 278, in app
[FD]     raw_response = await run_endpoint_function(
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
[FD]     return await run_in_threadpool(dependant.call, **values)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
[FD]     return await anyio.to_thread.run_sync(func, *args)
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
[FD]     return await get_async_backend().run_sync_in_worker_thread(
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
[FD]     return await future
[FD]   File "D:\Slicer\5.6.2\Slicer 5.6.2\lib\Python\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
[FD]     result = context.run(func, *args)
[FD]   File "D:\Slicer\MedSAMSlicer-master\server_essentials\server.py", line 326, in infer
[FD]     res[csidx], bbox_1024_prev = inf(bbox_1024_prev)
[FD]   File "D:\Slicer\MedSAMSlicer-master\server_essentials\server.py", line 321, in inf
[FD]     mask = medsam_inference(medsam_model, embeddings[csidx], bbox_1024_prev, H, W)
[FD] IndexError: list index out of range
I hope to get your help, thank you very much.

**Comment by rasakereh** [comment]
@gaolidan  thank you for sharing this. If there is no privacy issue, would you please share the image file with me via reza.asakereh@uhn.ca? Thanks
