### ISSUE TITLE
Extension doesn't stay installed

### ISSUE THREAD

**Issue by zemmyang** [bowang-lab/MedSAMSlicer#44]
- I open Slicer
- I install the extension using Developer Tools -> Extension Wizard -> Select Extension
- Extension is installed and I can use it
- I close Slicer
- I re-open Slicer in the same method that I originally opened it (in my case, through the CLI)
- MedSAM2 is no longer installed

I installed MedSAM through the same method and it stays installed in Slicer upon re-opening, so something different must be with MedSAM2

**Comment by rasakereh** [comment]
Can you check the "Additional Module Paths" after importing and after re-opening slicer? To view "Additional Module Paths":
`Edit > Application Settings > Modules > Additional Module Paths`
You should see a list of paths and SAM2 directory should be there both times. Lmk the result

**Comment by lzhangsh** [comment]
ya, I had the same issue:
![image](https://github.com/user-attachments/assets/d07527d9-2615-498e-8025-284a6bdb595b)
![image](https://github.com/user-attachments/assets/9db649a9-95f8-4e44-8875-90c73c26325c)
![image](https://github.com/user-attachments/assets/153ae131-b8f9-4ce5-9894-125f6bc8510e)

I guess there could be some issue while installing the environment though. I used CUDA12.1 on my RTX A4000. 
1) it failed executing """pip install -e ."""
![image](https://github.com/user-attachments/assets/d3030587-9a19-401e-b2a1-87b89c35e8ab)
but I did have numpy in the environment
![09b93fd8c5a0f0c0409f42575c33a04b](https://github.com/user-attachments/assets/5a614648-16a9-4885-ab45-540184846659)
2) because it failed on """pip install -e .""", I tried """python setup.py install""" and manually downloaded the dependent tools
![image](https://github.com/user-attachments/assets/844875d6-ceb7-4d62-9fd1-ea85e4c59a7d)
![image](https://github.com/user-attachments/assets/e5fad939-e19c-4fe0-bd51-8bc567618026)
I'm not sure whether the installation works cause it has such a warning
![image](https://github.com/user-attachments/assets/c88d4d71-1f3d-4560-857b-5b67cc42fa24)

**Comment by rasakereh** [comment]
SAM2 development is discontinued and MedSAM2 has replaced it. Can you try with this version and let me know if the problem is still there.
Link: [https://github.com/bowang-lab/MedSAMSlicer/tree/MedSAM2](https://github.com/bowang-lab/MedSAMSlicer/tree/MedSAM2)

**Make sure that you are using a clean workspace for installation to prevent collisions with SAM2**

**Comment by lzhangsh** [comment]
ya, it was totally an environment related error. Now it works (But I also changed a few lines of code. I had the same issue with openCV during the resize step and so I just commented it out, since there was no specific reason for me to interpolate the image to size 1024x1024.
1) I cleaned out all versions of torch_cuda and its dependencies; reinstalled everything --> IMPORTANT: remember to double check the CUDA_PATH in your windows system environment. Control Panel -> System and variables -> System -> Advanced Environment Settings -> check both path and the CUDA_PATH to ensure the cudatoolkit matches with the version of pip install in your pycharm
2) upgraded to Slicer5.6, I did use Slicer 5.0 at the very beginning
