### ISSUE TITLE
Dependencies installation :  Firewall Restrictions

### ISSUE THREAD

**Issue by sarrabenyahia** [bowang-lab/MedSAMSlicer#9]
Hello, 

I am currently facing a challenge with a restrictive firewall at my workplace, which prevents me from using the terminal to install packages directly from the internet. In my development workflow, I have been able to work around similar restrictions by downloading wheel (.whl) files of Python packages, transferring them to my local environment, and then installing them manually using pip.

Due to this, I can't use the "Install dependencies" button in Slicer.
Is there a similar way to prepare the environment and install it locally?

Thank you

**Comment by rasakereh** [comment]
Hi @sarrabenyahia , thank you for your feedback. I can provide you with a list of packages we rely on but I am pretty sure it would fail. The reason is that while installing using pip, you can think of multi-level dependencies (i.e package A needs B and B needs C, installing A will automatically installs other two.) It's gonna be a little challenging to do that. However the following link is the first level of dependencies that our plugin needs:

"monai", "matplotlib", "scikit-image", "SimpleITK>=2.2.1", "nibabel", "tqdm", "scipy", "ipympl", "opencv-python", "jupyterlab", "ipywidgets", "timm"

'torch==2.0.1 torchvision==0.15.2'
'numpysocket'
'fastapi'
'uvicorn'
